<div class="container">
	<div class="row">
<?php foreach($this->photos as $photo):?>
	<div class="col-sm-3">
		<a href='' class="thumbnail" onclick="window.opener.CKEDITOR.tools.callFunction(<?php echo $this->funcNum?>, '<?php echo $this->server ?>/images/upload/<?php echo $photo->id_article?>/<?php echo $photo->id_photo?>.<?php echo $photo->extension?>');window.close();return false;">
			<img src='/images/upload/<?php echo $photo->id_article?>/smallthumb<?php echo $photo->id_photo?>.<?php echo $photo->extension?>' alt='photo_<?php echo $photo->id_photo?>' />
		</a>
	</div>
<?php endforeach?>
	</div>
</div>
<script type='text/javascript'>
$(function(){
	$('hr:last').remove();
});
</script>