<?php if ($this->pageCount > 1): ?>
	<div class="paginationControl">
		<?php if (isset($this->previous)): ?>
			<a href="<?php echo $this->url(array('p'=>$this->previous)); ?>">Précédent</a>
		<?php else: ?>
			<button disabled="disabled">Précédent</button>
		<?php endif; ?>
		 
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<a href="<?php echo $this->url(array('p'=>$page)); ?>"><?php echo $page; ?></a>
			<?php else: ?>
				<button disabled="disabled"><?php echo $page; ?></button>
			<?php endif; ?>
		<?php endforeach; ?>
		 
		<?php if (isset($this->next)): ?>
			<a href="<?php echo $this->url(array('p'=>$this->next)); ?>">Suivant</a>
		<?php else: ?>
			<button disabled="disabled">Suivant</button>
		<?php endif; ?>
	</div>
<?php endif; ?>