<form method="post" action="<?= $_SERVER["REQUEST_URI"] ?>">
    <div class="modal-body">
        <div class="form-group">
            <h3>Etes vous sur ?</h3>
            <?= $this->formHidden('id_post',$this->access_code->id); ?>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
        <button type="submit" class="btn btn-danger">Supprimer</button>
    </div>
</form>