<ul class="myTab nav nav-tabs">
    <li class="<?= $this->state == Aurel_Table_Invitation::TYPE_SENT ? 'active' : '' ?>"><a href='<?= $this->url() ?>?state=<?= Aurel_Table_Invitation::TYPE_SENT ?>'>Invitations envoyées</a></li>
    <li class="<?= $this->state == Aurel_Table_Invitation::TYPE_VALIDATED ? 'active' : '' ?>"><a href='<?= $this->url() ?>?state=<?= Aurel_Table_Invitation::TYPE_VALIDATED ?>'>Invitations validées</a></li>
</ul>
<div class="nav-tabs-content">
    <?php if ($this->state == Aurel_Table_Invitation::TYPE_SENT) : ?>
        <div class="text-right">
            <a class="btn btn-primary btn-sm relance" data-loading-text="Envoi en cours..." href="<?= $this->url(['action' => 'resend']) ?>">Relancer tout le monde</a>
        </div>
    <?php endif; ?>
    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>Email inviteur</th>
                <th>Etat</th>
                <th>Date action</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->invitations as $invitation) : ?>
                <?= $this->partial("index/_line.phtml", ['invitation' => $invitation]) ?>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    $(function() {
        $('.relance').click(function() {
            $(this).button('loading');
        });
        <?php if ($this->ready) : ?>
            setInterval(function() {

                $.get(
                    '<?= $this->url(['action' => 'check-ready']) ?>',
                    function(response) {
                        if (response.refresh) {
                            location.reload();
                        }
                    }, 'json'
                );
            }, 5000);
        <?php endif; ?>

    });
</script>