<form class="form-horizontal" role="form" method="post" action="<?php echo $_SERVER["REQUEST_URI"]?>">
	<?php if($this->message):?>
		<div class="alert alert-danger text-center"><?php echo $this->message?></div>
	<?php endif?>
	<div>
		<h2 class="text-center">Connexion Administrateur</h2>
		<?php if($this->displayMessage):?>
		<div class="alert alert-danger">
			<?php echo $this->message?>
		</div>
		<?php endif?>
		<div class="form-group">
			<?php echo $this->formLabel('username','Identifiant / Email',array("class"=>"col-sm-2 control-label"))?>
			<div class="col-sm-10">
				<?php echo $this->formText('username',null,array("class"=>"form-control","placeholder"=>"Identifiant / Email"))?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel('pass','Password',array("class"=>"col-sm-2 control-label"))?>
			<div class="col-sm-10">
				<?php echo $this->formPassword('pass',null,array("class"=>"form-control","placeholder"=>"Password"))?>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
			<?php echo $this->formSubmit('envoyer','Connexion',array("class"=>"btn btn-default"))?>
			</div>
		</div>
	</div>
</form>
<script>
$(function(){

});
</script>