<form method="post" role="form" id="frmContact">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title" id="myModalLabel">Envoyer un message à <?php echo $this->annuaire_fiche->mail?></h4>
	</div>
	<div class="modal-body">
		<div class="form-group has-feedback">
			<?php echo $this->formLabel('email','Saisissez votre email',array('class'=>'control-label'))?>
			<?php echo $this->formText('email',null,array('class'=>'form-control'))?>
			<span class="message text-danger"></span>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel('text','Saisissez votre message',array('class'=>'control-label'))?>
			<?php echo $this->formTextarea('text',null,array('class'=>'form-control','rows'=>6))?>
			<span class="message text-danger"></span>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="cancel btn btn-default" data-dismiss="modal">Annuler</button>
		<?php echo $this->formSubmit('valider','Envoyer',array('class'=>'btn btn-primary','data-loading-text'=>"Loading..."))?>
	</div>
</form>
<script type="text/javascript">
	$(function(){
		$("#frmContact").submit(function(){
			$('#valider').button('loading');
			$('.form-group').removeClass('has-error').removeClass('has-success');
			$('.message').html('');
			
			$.post(
				'<?php echo $this->url()?>',
				$(this).serialize(),
				function(transport){
					if(transport.errors){
						for(i in transport.errors){
							var elt = transport.errors[i];
							$('#'+elt).parent().addClass('has-error').find('.glyphicon').removeClass('hidden').addClass('glyphicon-remove');
							if(transport.message[elt])
								$('#'+elt).parent().find('.message').html(transport.message[elt]);
						}
					}
					if(transport.sent){
						$('#frmContact .modal-body').html("Votre message a été envoyé");
						$('#valider').remove();
						$('.cancel').html("Fermer").removeClass('btn-default').addClass('btn-primary');
					}
					$('#valider').button('reset');
				},'json'
			);
			return false;
		});
	});
</script>