<?php if($this->fiches->count() > 0):?>
<?php foreach($this->fiches as $fiche):?>
	<div class="ficheannuaire media row article thumbnail <?php echo $fiche->status == Aurel_Table_AnnuaireFiche::STATUS_INACTIF ? "inactive" : ""?> <?php echo $fiche->status == Aurel_Table_AnnuaireFiche::STATUS_WAITING ? "waiting" : ""?>" id="fiche-<?php echo $fiche->id_annuaire_fiche?>">
		<?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ANNUAIRE)):?>
		<div class="actions btn-group-sm">
			<input type="checkbox" value="<?php echo $fiche->id_annuaire_fiche?>" class="checkboxSwitch" <?php echo $fiche->status == Aurel_Table_AnnuaireFiche::STATUS_ACTIF ? "checked='checked'" : ""?> />
			<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
				Actions <span class="caret"></span>
			</button>
			<ul class="dropdown-menu dropdown-menu-right" role="menu">
				<?php if($fiche->status == Aurel_Table_AnnuaireFiche::STATUS_WAITING):?><li><a class='activeFiche' href="<?php echo $this->url(array('action'=>'toggle-fiche','controller'=>'annuaire','id_annuaire_fiche'=>$fiche->id_annuaire_fiche,'state'=>'true'),'admin',true)?>"><span class="glyphicon glyphicon-ok"></span> Valider</a></li><?php endif?>
				<li><a class='modifFiche' href='<?php echo $this->url(array('action'=>'edit-fiche','id_annuaire_fiche'=>$fiche->id_annuaire_fiche,'basenamesouscategorie'=>$fiche->basename_sous_categorie,'basenamecategorie'=>$fiche->basename_categorie,'url_retour'=>urlencode($_SERVER["REQUEST_URI"])),'annuaire')?>'><span class="glyphicon glyphicon-pencil"></span> Modifier fiche</a></li>
				<li class="divider"></li>
				<li><a class='supFiche' href='<?php echo $this->url(array('action'=>'delete-fiche','controller'=>'annuaire','id_annuaire_fiche'=>$fiche->id_annuaire_fiche,'url_retour'=>urlencode($_SERVER['REQUEST_URI'])),'admin',true)?>?comHash=<?php echo md5($fiche->id_annuaire_fiche)?>' title="Supprimer fiche"><span class="glyphicon glyphicon-remove"></span> Supprimer</a></li>
			</ul>
		</div>
		<?php elseif($this->tabRights[$fiche->id_annuaire_fiche]):?>
		<div class="actions btn-group-sm">
			<a class='modifFiche btn btn-primary' href='<?php echo $this->url(array('action'=>'edit-fiche','id_annuaire_fiche'=>$fiche->id_annuaire_fiche,'basenamesouscategorie'=>$fiche->basename_sous_categorie,'basenamecategorie'=>$fiche->basename_categorie,'url_retour'=>urlencode($_SERVER["REQUEST_URI"])),'annuaire')?>'><span class="glyphicon glyphicon-pencil"></span> Mise à jour</a>
		</div>
		<?php endif?>
		<div class="col-md-3">
			<div class="visuel">
                <?php if($fiche->picture):?>
                    <a class="popupVideo" data-toggle="modal" data-target="#myLargeModal" href='<?php echo $this->url(array('action'=>'diaporama','id_annuaire_fiche'=>$fiche->id_annuaire_fiche),'action',true)?>'>
                        <?php if($fiche->nbPhotos > 1):?>
                            <div class="cycle-slideshow" data-cycle-speed="200" data-cycle-timeout="1000" style="">
                                <?php foreach($fiche->getIdPhotos(10) as $key=>$id_photo):?>
                                    <img class="<?php echo $key == 0 ? " " : "hidden "?>img-responsive" src='/images/upload/fiche_<?php echo $fiche->id_annuaire_fiche?>/thumb<?php echo $id_photo?>' alt='image<?php echo $fiche->id_annuaire_fiche?>' />
                                <?php endforeach;?>
                            </div>
                            <div class="nbPhotos">
                                <span class="glyphicon glyphicon-camera"></span> <?php echo $fiche->nbPhotos?>
                            </div>
                        <?php else:?>
                            <img class="img-responsive" src='/images/upload/fiche_<?php echo $fiche->id_annuaire_fiche?>/thumb<?php echo $fiche->picture?>.<?php echo $fiche->extension?>' alt='image<?php echo $fiche->id_annuaire_fiche?>'/>
                        <?php endif?>
                    </a>
                <?php else: ?>
                    <img class="img-responsive" src='/images/no-photo-fiche.jpg' alt='image<?php echo $fiche->id_annuaire_fiche?>' />
                <?php endif?>
			</div>
			<div class="aplat" style="background-color:<?php echo "#" . $fiche->color_code ?>">
				<?php echo $fiche->name_sous_categorie?>
			</div>
		</div>
		<div class="content col-md-9" id="fiche<?php echo $fiche->id_annuaire_fiche?>">
			<?php /*?><div style="height:5px;background-color:<?php echo "#" . $fiche->color_code; ?>"></div>*/?>
			<div><h3 class="underline" style="margin-top:5px"><?php echo mb_strtoupper($fiche->nom_etablissement);?></h3></div>
			<div class="">
				<div class=""><?php echo $fiche->adresse_1;?></div>
				<div class=""><?php echo $fiche->adresse_2;?></div>
				<div class=""><?php echo $fiche->code_postal;?> <?php echo $fiche->ville;?></div>
				<?php if($fiche->website):?>
					<?php $url = $fiche->website?>
					<?php $site = str_replace("http://","",$url)?>
					<?php $site = str_replace("https://","",$site)?>
					<div><a target="_blank" href='<?php echo $url?>'><?php echo $site?></a></div>
				<?php endif?>
			</div>
			
			<div class="" style="margin-top : 10px;"></div>
			<?php if($fiche->descriptif):?>
			<fieldset class="telechargements">
				<legend>Description</legend>
				<div><?php echo nl2br($fiche->descriptif);?></div>
			</fieldset>
			<?php endif?>
			<?php if($fiche->horaires):?>
			<fieldset class="telechargements">
				<legend>Horaires</legend>
				<div><?php echo nl2br($fiche->horaires);?></div>
			</fieldset>
			<?php endif?>
			<?php if($fiche->contact_nom || $fiche->contact_prenom || $fiche->tel_1|| $fiche->tel_2 || $fiche->mail):?>
			<fieldset class="telechargements">
				<legend>Contact</legend>
				<div class=''>
					<div><strong><?php echo $fiche->contact_nom?> <?php echo $fiche->contact_prenom?></strong></div>
					<?php if($fiche->tel_1):?><div><span class="glyphicon glyphicon-earphone"></span> Tel : <?php echo $fiche->tel_1?></div><?php endif?>
					<?php if($fiche->tel_2):?><div><span class="glyphicon glyphicon-phone"></span> Tel : <?php echo $fiche->tel_2?></div><?php endif?>
					<?php if($fiche->mail):?><div><span class="glyphicon glyphicon-envelope"></span> Email : <a class="" data-toggle="modal" data-target="#myModal" href='<?php echo $this->url(array('action'=>'contact','id_annuaire_fiche'=>$fiche->id_annuaire_fiche,'basenamesouscategorie'=>$fiche->basename_sous_categorie,'basenamecategorie'=>$fiche->basename_categorie),'annuaire',true)?>'><?php echo $fiche->mail?></a></div><?php endif?>
				</div>
			</fieldset>
			<?php endif?>
		</div>
	</div>
<?php endforeach;?>
<?php else:?>
	<div class="jumbotron">
  		<h2>Aucune fiche dans cette catégorie<?php if($this->q):?> avec la recherche :<?php endif?></h2>
  		<?php if($this->q):?>
  			<h4 class="text-center"><?php echo $this->q?></h4>
  			<div class="text-center"><a class="deleteSearch2 btn btn-primary" href='#'>Retirer le paramètre "<?php echo $this->q?>"</a></div>
  		<?php endif?>
	</div>
<?php endif?>
<script type="text/javascript">
$(function(){
	$('.deleteSearch2').click(function(){
		var url = $('#searchForm').prop('action');
		if(url.indexOf("?") != '-1')
			url = url.slice(0, url.indexOf("?"));
		$('#q').val('');
		$('.waitings').fadeIn();
		$.post(
			url,
			function(response){
				history.pushState(null, null, url);
				$('#searchForm').prop('action',url);
				$('.bs-docs-sidenav a').each(function(){
					var href = $(this).prop('href');
					href = href.slice(0, href.indexOf("?"));
					$(this).prop('href',href);
				});
				$('.toFill').html(response).fadeIn();
				$('.waitings').hide();
			}
		);
		return false;
	});
	<?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ANNUAIRE)):?>
	$(".checkboxSwitch").bootstrapSwitch();
	$(".checkboxSwitch").on('switchChange.bootstrapSwitch', function(event, state) {
		  var id_annuaire_fiche = $(this).val();
		  $.post(
			"<?php echo $this->url(array('action'=>'toggle-fiche','controller'=>'annuaire'),'admin',true)?>",
			{"id_annuaire_fiche":id_annuaire_fiche,"state":state},
			function(response){
				if(response.returncode == 'ok'){
					$('#fiche-' + id_annuaire_fiche).removeClass('waiting').removeClass('inactive');
					$('#fiche-' + id_annuaire_fiche).addClass(response.classCss);
				}
			},'json'
		  );	
	});
	$('.activeFiche').click(function(){
		$(this).parent().parent().parent().find('.checkboxSwitch').bootstrapSwitch('state', true, true);
		$.post(
			$(this).prop('href'),
			function(response){
				if(response.returncode == 'ok'){
					$('#fiche-' + response.id_annuaire_fiche).removeClass('waiting').removeClass('inactive');
					$('#fiche-' + response.id_annuaire_fiche).addClass(response.classCss);
					$('#fiche-' + response.id_annuaire_fiche + ' .activeFiche').remove();
					$('#fiche-' + response.id_annuaire_fiche + ' .actions').removeClass('open');
				}
			},'json'
		);
		return false;
	});
	$('.supFiche').click(function(){
		return confirm("Etes vous sur de vouloir supprimer cet article ?");
	});
	<?php endif?>
});
</script>