<div class="row">
	<div class="col-xs-offset-1 col-xs-3">
		<img class="img-responsive" src='/images/layout/couverture_annuaire_thumb.jpg' alt="Couverture" />
	</div>
	<div class="col-xs-8 frmConnexion">
	<form id="frmConnexion" class="" role="form" method="post" action="<?php echo $_SERVER["REQUEST_URI"]?>">
		<?php if($this->message):?>
			<div class="alert alert-danger text-center"><?php echo $this->message?></div>
		<?php endif?>
		<div>
			<div class="modal-header">
				<h2 class="">Accès restreint</h2>
				<h4 class="">Merci de saisir le mot de passe "Accès annuaire" <br/>qui vous a été fourni afin de mettre à jour, valider votre fiche.</h4>
                ou contactez nous sur redaction@lepetitcharsien.com pour obtenir votre code d'accès
			</div>
			<div class="modal-body">
			<div class="form-group">
				<?php echo $this->formLabel('pass','Mot de passe',array("class"=>"control-label"))?>
				<?php echo $this->formPassword('pass',null,array("class"=>"form-control","placeholder"=>"Mot de passe"))?>
			</div>
			<div class="form-group">
				<?php echo $this->formSubmit('envoyer','Connexion',array("class"=>"btn btn-primary","data-loading-text"=>"Connexion en cours..."))?>
			</div>
			</div>
		</div>
	</form>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		$('#frmConnexion').submit(function(){
			$('#envoyer').button('loading');
		});
		<?php if($this->emailLogin):?>
			$('#pass').focus();
		<?php endif?>
	});
</script>