<form id="frmConnexion" class="form-horizontal" role="form" method="post" action="<?php echo $_SERVER["REQUEST_URI"]?>">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title" id="myModalLabel">Connexion</h4>
	</div>
	<div class="modal-body">
		<div>
			<?php if($this->displayMessage):?>
			<div class="alert alert-danger">
				<?php echo $this->message?>
			</div>
			<?php endif?>
			<div class="form-group">
				<?php echo $this->formLabel('username','Email',array("class"=>"col-sm-2 control-label"))?>
				<div class="col-sm-10">
					<?php echo $this->formText('username',$this->emailLogin,array("class"=>"form-control","placeholder"=>"Email"))?>
				</div>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel('pass','Password',array("class"=>"col-sm-2 control-label"))?>
				<div class="col-sm-10">
					<?php echo $this->formPassword('pass',null,array("class"=>"form-control","placeholder"=>"Password"))?>
				</div>
			</div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label class="control-label">
                            <?php echo $this->formCheckbox('remember',null,array('checked'=>true))?> Se souvenir de moi
                        </label>
                    </div>
                </div>
            </div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<a href='<?php echo $this->url(array('action'=>'passoublie','url_redirect'=>null))?>'>Mot de passe oublié ?</a>
				</div>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
		<?php echo $this->formSubmit('envoyer','Connexion',array("class"=>"btn btn-primary","data-loading-text"=>"Connexion en cours..."))?>
	</div>
</form>

<script type="text/javascript">
	$(function(){
		$('#frmConnexion').submit(function(){
			$('#envoyer').button('loading');
		});
		<?php if($this->emailLogin):?>
			$('#pass').focus();
		<?php endif?>
	});
</script>