<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title" id="myModalLabel">Inscription Newsletter</h4>
</div>
<div class="modal-body">
	<strong>Votre inscription a bien été enregistrée</strong>
</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
</div>
	
