<?php echo $this->render('compte/tabs.phtml')?>
<div class="nav-tabs-content">
	<ul class="myTab2 nav nav-tabs" role="tablist">
		<li class="active"><a role="tab" data-toggle="tab" href='#futur'>Inscriptions en cours</a></li>
		<li class=""><a role="tab" data-toggle="tab" href='#historique'>Historique Inscriptions</a></li>
	</ul>
	<div class="tab-content nav-tabs-content">
		<div class="tab-pane active fade in" id="futur">
			<table class="table">
				<thead>
					<tr>
						<th>Evenement</th>
						<th>Date événement</th>
						<th>Total</th>
						<th>Commentaire</th>
						<th>Date inscription</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->tabSortie as $id_article => $article):?>
					<tr>
						<td><a href='<?php echo $this->url(array('basename_article'=>$article['basename']),'basename_article',true)?>'><?php echo $article['title']?></a></td>
						<td><?php echo $article['start_date']->get(Aurel_Date::DATE_SHORT)?></td>
						<td><?php echo $article['total']?></td>
						<td><?php echo $article['comment']?></td>
						<td><?php echo $article['date_inscription']->get(Aurel_Date::DATETIME_SHORT)?></td>
						<td>
							<a data-toggle="modal" data-target="#myModal" title="Voir les inscrits" class="tool btn btn-primary btn-sm" href="<?php echo $this->url(array('action'=>'synthese-inscription','id_article'=>$id_article),'action',true)?>"><span class="glyphicon glyphicon-user"></span></a>
							<a data-toggle="modal" data-target="#myModal" title="Modifier mon inscription" class="tool btn btn-primary btn-sm" href="<?php echo $this->url(array('action'=>'participer','id_article'=>$id_article,'url_retour'=>urlencode($_SERVER["REQUEST_URI"])),'action',true)?>"><span class="glyphicon glyphicon-pencil"></span></a>
							<a title="Annuler mon inscription" class="confirm tool btn btn-danger btn-sm" href="<?php echo $this->url(array('action'=>'cancel-inscription','id_article'=>$id_article,'url_retour'=>urlencode($_SERVER["REQUEST_URI"])),'action',true)?>"><span class="glyphicon glyphicon-remove"></span></a>
						</td>
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
		<div class="tab-pane fade" id="historique">
			<table class="table">
				<thead>
					<tr>
						<th>Evenement</th>
						<th>Date événement</th>
						<th>Total</th>
						<th>Commentaire</th>
						<th>Date inscription</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->tabSortieHistorique as $id_article => $article):?>
					<tr>
						<td><a href='<?php echo $this->url(array('basename_article'=>$article['basename']),'basename_article',true)?>'><?php echo $article['title']?></a></td>
						<td><?php echo $article['start_date']->get(Aurel_Date::DATE_SHORT)?></td>
						<td><?php echo $article['total']?></td>
						<td><?php echo $article['comment']?></td>
						<td><?php echo $article['date_inscription']->get(Aurel_Date::DATETIME_SHORT)?></td>
						<td>
							<a data-toggle="modal" data-target="#myModal" title="Voir les inscrits" class="tool btn btn-primary btn-sm" href="<?php echo $this->url(array('action'=>'synthese-inscription','id_article'=>$id_article),'action',true)?>"><span class="glyphicon glyphicon-user"></span></a>
							<a class='btn btn-primary' href='<?php echo $this->url(array('controller'=>'articles','action'=>'download-synthese','id_article'=>$id_article),'admin',true)?>'>Télécharger le reporting (fichier CSV)</a>
						</td>
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		<?php if($this->modal_url):?>
			$('#myModal .modal-content').load('<?php echo $this->modal_url; ?>');
			$('#myModal').modal('show');
		<?php endif?>
		$('.tool').tooltip();
		$('.confirm').click(function(){
			return confirm("Êtes vous sur de vouloir annuler cette inscription ?");
		});

		<?php if($this->valideParticipation == '1'):?>
			$('#mySmallModal .modal-content').html('<div class="modal-body"><div class="text-center">Votre participation a bien été prise en compte</div></div><div class="modal-footer"><button type="button" class="btn btn-primary" data-dismiss="modal">Fermer</button></div>');
			$('#mySmallModal').modal('show');
		<?php endif?>

		var hash = window.location.hash;
		if(hash){
			$('.myTab2 a[href="'+hash+'"]').tab('show');
		}
		$('.myTab2 a').click(function(){
			var hashLink = $(this).prop('href').replace("http://<?php echo $_SERVER['HTTP_HOST']?><?php echo $_SERVER['REQUEST_URI']?>","");
			window.location.hash = hashLink;
		});
	});
</script>