<div class="bg-white px-5 py-4 mt-5 mb-5">
    <div class='text-primary h3 font-weight-bolder text-center'>
        <?= $this->message ?>
    </div>
    <div class="mt-3" style="margin-top:20px;">
        <small class=''>
            Pour obtenir plus d'informations, contactez le support : <a class="font-weight-bold" href='mailto:support@sponsoring-credit-agricole.fr'>support@sponsoring-credit-agricole.fr</a>
        </small>
    </div>
</div>
<?php if (!$this->novalidation) : ?>
    <form id="frmValidUser" method='post' action='<?= $_SERVER["REQUEST_URI"] ?>'>
        <button type='submit' style="display:none">Valider</button>
    </form>
    <script>
        grecaptcha.ready(function() {
            grecaptcha.execute('6LcZ1hAdAAAAADpsWPRZc-jfD5O4m2Y1md8tmO3K', {
                action: 'create_comment'
            }).then(function(token) {
                $('#frmValidUser').prepend('<input type="hidden" name="g-recaptcha-response" value="' + token + '">');
                $('#frmValidUser').submit();
            });
        });
    </script>
<?php endif; ?>