<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title" id="myModalLabel"><?php echo $this->article->title?></h4>
</div>
<div class="modal-body">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	  	<?php foreach($this->photos as $key=>$photo):?>
	  		<li data-target="#carousel-example-generic" data-slide-to="<?php echo $key; ?>" <?php echo $key == 0 ? "class='active'" : ""?>></li>
		<?php endforeach;?>
	  </ol>
	
	  <!-- Wrapper for slides -->
	  <div class="carousel-inner">
	    <?php foreach($this->photos as $key=>$photo):?>
	  		<div class="item <?php echo $key == 0 ? "active" : ""?>">
		      <img class="img-responsive center-block" src='/images/upload/<?php echo $photo->id_article?>/<?php echo $photo->id_photo?>.<?php echo $photo->extension?>' alt='photo_<?php echo $photo->id_photo?>' />
		    </div>
		<?php endforeach;?>
	  </div>
	
	  <!-- Controls -->
	  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left"></span>
	  </a>
	  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right"></span>
	  </a>
	</div>
</div>

<script type="text/javascript">
$(function(){
	
});
</script>