<div class="homeLink text-center">
    <img src="/images/upload/home.jpg" class="img-responsive center-block"/>
</div>
<?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES)):?>
    <form id="frmuploadphoto" method="post" class="form-horizontal" role="form" enctype="multipart/form-data" action="<?php echo $this->url(array("controller"=>"photos","action"=>"upload-photo-site","page"=>"home"),"admin",true) ?>">
        <div class="blockUploadPhoto text-center">
            <div class="wait hidden"><img src='/images/wait.gif' alt='wait' /></div>
            <div class="header text-center">Modifier photo</div>
            <div class="buttonUpload text-center">
                <?php echo $this->formButton("buttonfile","Choisir le fichier",array('class'=>'btn btn-success btn-xs'))?>
            </div>
            <input type="file" class="inputFilePhoto" name="photo" />
            <?php echo $this->formHidden("file",'home',array('class'=>'fileHidden'))?>

            <div class="progress center-block" style="width: 150px;display: none">
                <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                    <span class="number">0</span>%
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        $(function(){
            $('.inputFilePhoto').change(function(){
                var Formdata = new FormData($("#frmuploadphoto")[0]);

                $.ajax({
                    url: "<?php echo $this->url(array("controller"=>"photos","action"=>"upload-photo-site","page"=>"home"),"admin",true) ?>",
                    data: Formdata,
                    cache: false,
                    contentType: false,
                    processData: false,
                    dataType : 'json',
                    type: 'POST',
                    beforeSend: function () {
                        $('.progress .progress-bar').css('width','0%').prop('aria-valuenow',0);
                        $('.progress').fadeIn();
                    },
                    xhr: function () {
                        var xhr = new window.XMLHttpRequest();
                        //Download progress
                        xhr.addEventListener("progress", function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round(evt.loaded * 100 / evt.total);
                                $('.progress .progress-bar').css('width',percentComplete + '%').prop('aria-valuenow',percentComplete);
                                $('.progress .progress-bar .number').text(percentComplete);
                            }
                        }, false);
                        return xhr;
                    },
                    success: function(response){
                        if(response.message){
                            $("#messages").html(response.message);
                            if(response.valid == true){
                                $("#messages").addClass('alert alert-success');
                            } else {
                                $("#messages").addClass('alert alert-danger');
                            }
                        }
                        if(response.picture_url){
                            $('.homeLink img').fadeOut(400,function(){
                                $('.homeLink img').prop('src',response.picture_url);
                                $('.homeLink img').fadeIn();
                            });
                        }
                        if(response.filename){
                            $('#picturetmp').val(response.filename);
                        }
                        if(response.creation == "0"){
                            $('.progress').fadeOut();
                            $('#myPopupMessage .modal-content h3').text('Photo envoyée');
                            $('#myPopupMessage').modal('show');
                        }
                    }
                });
            });
        });
    </script>
<?php endif?>