
<?php if ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES)): ?>
    <form id="frmuploadphoto" method="post" class="form-horizontal" role="form" enctype="multipart/form-data" action="<?php echo $this->url(array("controller" => "photos", "action" => "upload-photo-site", "page" => "home"), "admin", true) ?>">
        <div class="blockUploadPhoto text-center">
            <div class="wait hidden"><img src='/images/wait.gif' alt='wait' /></div>
            <div class="header text-center">Modifier photo</div>
            <div class="buttonUpload text-center">
                <?php echo $this->formButton("buttonfile", "Choisir le fichier", array('class' => 'btn btn-success btn-xs')) ?>
            </div>
            <input type="file" class="inputFilePhoto" name="photo" />
            <?php echo $this->formHidden("file", 'home', array('class' => 'fileHidden')) ?>

            <div class="progress center-block" style="width: 150px;display: none">
                <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                    <span class="number">0</span>%
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        $(function () {
            $('.inputFilePhoto').change(function () {
                var Formdata = new FormData($("#frmuploadphoto")[0]);

                $.ajax({
                    url: "<?php echo $this->url(array("controller" => "photos", "action" => "upload-photo-site", "page" => "home"), "admin", true) ?>",
                    data: Formdata,
                    cache: false,
                    contentType: false,
                    processData: false,
                    dataType: 'json',
                    type: 'POST',
                    beforeSend: function () {
                        $('.progress .progress-bar').css('width', '0%').prop('aria-valuenow', 0);
                        $('.progress').fadeIn();
                    },
                    xhr: function () {
                        var xhr = new window.XMLHttpRequest();
                        //Download progress
                        xhr.addEventListener("progress", function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round(evt.loaded * 100 / evt.total);
                                $('.progress .progress-bar').css('width', percentComplete + '%').prop('aria-valuenow', percentComplete);
                                $('.progress .progress-bar .number').text(percentComplete);
                            }
                        }, false);
                        return xhr;
                    },
                    success: function (response) {
                        if (response.message) {
                            $("#messages").html(response.message);
                            if (response.valid == true) {
                                $("#messages").addClass('alert alert-success');
                            } else {
                                $("#messages").addClass('alert alert-danger');
                            }
                        }
                        if (response.picture_url) {
                            $('.homeLink img').fadeOut(400, function () {
                                $('.homeLink img').prop('src', response.picture_url);
                                $('.homeLink img').fadeIn();
                            });
                        }
                        if (response.filename) {
                            $('#picturetmp').val(response.filename);
                        }
                        if (response.creation == "0") {
                            $('.progress').fadeOut();
                            $('#myPopupMessage .modal-content h3').text('Photo envoyée');
                            $('#myPopupMessage').modal('show');
                        }
                    }
                });
            });
        });
    </script>
<?php endif ?>
<div class="homeLink text-center">
    <img src="/images/upload/home.jpg" class="img-responsive center-block"/>
    <img src="/images/upload/home.jpg" class="img-responsive center-block visible-xs">
    <div class="overlayBlack linkPronoteam">
        <h1><?= $this->config->title_link_prono ?></h1>
        <a class="btn btn-button" href="/pronostiques">PRONOSTIQUER <img src="/images/fleche.PNG" /></a>
    </div>
    <?php /*<div class="overlayBlack linkVouchers">
        <h1>COUPONS REDUCTION 20%</h1>
            <a class="btn btn-button" href="/vouchers">RECUPERER MON CODE <img src="/images/fleche.PNG" /></a>
    </div>*/ ?>
    <div class="overlayBlack linkInvitation">
        <h1>RECOMMANDER <br>
            Sportminedor MARCHE ENTREPRISES</h1>
            <a class="btn btn-button" href="/compte/invite">COOPTER DES CONTACTS <img src="/images/fleche.PNG" /></a>
    </div>
    <?php /*if($this->user->adresse_access): ?>
    <div class="overlayBlack linkInvitation">
        <h1>MON BALLON<br>EURO2020</h1>
            <a class="btn btn-button" href="/sondage/je-documente-mon-adresse-de-livraison">JE DOCUMENTE MON ADRESSE <img src="/images/fleche.PNG" /></a>
    </div>
    <?php endif;*/ ?>
</div>
<br/>
<div class="row">
    <div class="col-md-12 objetsActualite">
        <div id="articles" class="articles row" style="margin:0 15px 0 15px">
            <?php echo $this->render('index/articles-in-accueil.phtml') ?>
        </div>

        <div id="articles2" class="articles row" style="margin:0 15px 0 15px">
            <?php echo $this->render('index/articles2.phtml') ?>
        </div>
    </div>
</div>
<?php if (count($this->access_rapide) > 0): ?>
    <div class="titreImage">
        <img class="center-block img-responsive fondGris" src='/images/layout/footer.png' alt='Accès rapide' />
        <div class="bande_horizontale traitBleuFonce"></div>
    </div>
    <div class="container acces_rapide">
        <div class="hidden-xs">
            <ul class="row">
                <?php foreach ($this->access_rapide as $url => $link): ?>
                    <li class="col-xs-3 text-center"><a href='<?php echo $url ?>'><?php echo $link ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="visible-xs">
            <ul class="row">
                <?php foreach ($this->access_rapide as $url => $link): ?>
                    <li class="col-xs-6 text-center"><a href='<?php echo $url ?>'><?php echo $link ?></a></li>
                    <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif ?>
<script type="text/javascript">
    function initialisePage() {
        $('.cycle-slideshow').cycle();
        $('.cycle-slideshow').cycle('pause');
        $('.hover').hover(function () {
            $(this).find('.cycle-slideshow').cycle('resume').cycle('goto', 1);
        }, function () {
            $(this).find('.cycle-slideshow').cycle('pause').cycle('goto', 0);
        });
        $('.cycle-slideshow img').removeClass('hidden');
    }

    function scroll() {
        $(".month").off('mouseenter mouseleave');
        var scroller = null;
        $('.month').hover(function () {
            var thisOne = $(this);
            var widthMonth = $(this).width();
            var elt = $("<span class='scrollMonth' style='font-weight:bold'></span>").html($(this).find('.ellipsis').html());
            thisOne.find('.ellipsis').css("text-overflow", "initial");
            $('.scrollMonths').append(elt);
            var width = $('.scrollMonths .scrollMonth').width();
            $('.scrollMonths .scrollMonth').remove();

            var timing = (width + widthMonth + widthMonth) / 300;
            console.log(timing);

            if (width > widthMonth) {
                var scroll = width + widthMonth;
                var i = 0;
                scroller = setInterval(function () {
                    var textIndent = Number(thisOne.find('.ellipsis').css("margin-left").replace("px", ""));

                    if (textIndent > -scroll) {
                        thisOne.find('.ellipsis').css({"margin-left": -i});
                        i += timing;
                    } else {
                        thisOne.find('.ellipsis').css({"margin-left": widthMonth});
                        i = -widthMonth;
                    }
                }, 5);
            }
        }, function () {
            $('.scrollMonths .scrollMonth').remove();
            clearTimeout(scroller);
            var thisOne = $(this);
            thisOne.find('.ellipsis').css({"margin-left": 0, "text-overflow": "ellipsis"});
        });
    }

    function download() {
        $('.download-others').click(function () {
            var btn = $(this)
            btn.button('loading');
            $.get(
                    $(this).prop('href'),
                    function (response) {
                        if (response.html) {
                            $('.articles').append(response.html);
                        }
                        if (response.pagination) {
                            $('#pagination').html(response.pagination);
                        }
                        download();
                        btn.button('reset');
                        btn.blur();
                        initialisePage();
                    }, 'json'
                    );
            return false;
        });
    }
    $(function () {
        initialisePage();
        download();
        scroll();
<?php if ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES)): ?>
            $(".objetsActualite").sortable({
                items: "div.actualitesinfo",
                update: function (event, ui) {
                    order = $(this).sortable("toArray").toString();
                    $.post(
                            '<?php echo $this->url(array('action' => 'sort-articles', 'controller' => 'articles'), 'admin', true) ?>',
                            'order=' + order,
                            function (data, textStatus, XMLHttpRequest) {

                            }
                    );
                    initialisePage();
                }
            });
<?php endif ?>


    });
</script>