<div class="backgroundimage" style="background-image:url(/images/upload/<?php echo!$this->sousmenu ? 'menu' . $this->menu->id_menu . '/' . $this->menu->picture : 'sousmenu' . $this->sousmenu->id_sous_menu . '/' . $this->sousmenu->picture; ?>)">
    <?php if (!$this->ajax): ?>
        <?php if ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES)): ?>
            <form id="frmuploadphoto" method="post" class="form-horizontal" role="form" enctype="multipart/form-data" action="<?php echo $this->url(array("controller" => "photos", "action" => "upload-photo-site", "page" => "home"), "admin", true) ?>">
                <div class="blockUploadPhoto text-center">
                    <div class="wait hidden"><img src='/images/wait.gif' alt='wait' /></div>
                    <div class="header text-center">Modifier background</div>
                    <div class="buttonUpload text-center">
                        <?php echo $this->formButton("buttonfile", "Choisir le fichier", array('class' => 'btn btn-success btn-xs')) ?>
                    </div>
                    <input type="file" class="inputFilePhoto" name="photo" />
                    <?php echo $this->formHidden("file", 'home', array('class' => 'fileHidden')) ?>

                    <div class="progress center-block" style="width: 150px;display: none">
                        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                            <span class="number">0</span>%
                        </div>
                    </div>
                </div>
            </form>
        <?php endif ?>
        <div class="pictureTop">
            <a href="<?php echo $this->url(array(), 'accueil', true) ?>">Home</a> /
            <?php if (!$this->sousmenu): ?><a href="<?php echo $this->url(array('basename_principal' => $this->menu->basename), 'basenames', true) ?>"><?php endif ?><?php echo $this->menu->name ?><?php if (!$this->sousmenu): ?></a><?php endif ?>
            <?php if ($this->sousmenu && $this->menu): ?>
                / <a href="<?php echo $this->url(array('basename_principal' => $this->menu->basename, 'basename_secondaire' => $this->sousmenu->basename), 'basenames', true) ?>"><?php echo $this->sousmenu->name ?></a>
            <?php endif ?>
            <?php if ($this->article): ?>
                / <a href="<?php echo $this->url() ?>"><?php echo $this->article->title ?></a>
            <?php endif ?>
        </div>
        <?php if (($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES) || $this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_REDACTEUR) && isset($this->menus_redacteur[$this->menu->id_menu][$this->sousmenu->id_sous_menu]) && $this->menus_redacteur[$this->menu->id_menu][$this->sousmenu->id_sous_menu] == "1")): ?>
            <div class="text-center"><a class="btn btn-default addArticle" href='<?php echo $this->url(array('action' => 'edit-article', 'controller' => 'articles', 'id_article' => null, 'basename_principal' => $this->basename_principal, 'basename_secondaire' => $this->basename_secondaire, 'url_retour' => urlencode($this->url(array("basename_principal" => $this->basename_principal, 'basename_secondaire' => $this->basename_secondaire), "basenames", true))), 'admin', true) ?>'><span class="glyphicon glyphicon-plus"></span> Ajouter un article</a></div>
        <?php endif ?>
    <?php else: ?>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel"><?php echo $this->article->title ?></h4>
        </div>
        <div class="modal-body">
        <?php endif ?>
        <?php if ($this->isAllowed(Aurel_Acl::RESSOURCE_MEMBRE) && $this->article->annonce && $this->article->state_annonce == Aurel_Table_Article::STATE_ANNONCE_WAITING && $this->article->id_user_creation == $this->user->id_user): ?>
            <div class="alert alert-danger text-center">	
                Votre annonce est en attente d'évaluation
            </div>
            <br/>
        <?php elseif ($this->isAllowed(Aurel_Acl::RESSOURCE_MEMBRE) && $this->article->annonce && $this->article->state_annonce == Aurel_Table_Article::STATE_ANNONCE_REFUSED && $this->article->id_user_creation == $this->user->id_user): ?>
            <div class="alert alert-danger text-center">	
                Annonce refusée
            </div>
            <br/>
        <?php endif ?>
        <div id="popupArticles">
            <div class="articles">
                <?php if ($this->article->id_article): ?>
                    <div class="media row article articlemin" id="article-<?php echo $this->article->id_article ?>">
                        <?php if ($this->article->link_event && $this->article->start_date): ?>
                            <div class="date_cartouche">
                                <span class="day_of_month"><?php echo $this->article->getDate('start_date')->get(Aurel_Date::DAY) ?></span>
                                <span class="month_name"><?php echo mb_strtoupper($this->article->getDate('start_date')->get(Aurel_Date::MONTH_NAME_SHORT)) ?></span>
                            </div>
                        <?php endif ?>
                        <?php if (!$this->article->annonce): ?>
                            <?php if ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES) || ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_REDACTEUR) && $this->article->id_user_creation == $this->user->id_user)): ?>
                                <div class="actions btn-group-sm">
                                    <input type="checkbox" value="<?php echo $this->article->id_article ?>" class="checkboxSwitch" <?php echo $this->article->status == Aurel_Table_Article::STATUS_ACTIF ? "checked='checked'" : "" ?> />
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                        Actions <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                        <?php if(!$this->article->hide_home):?><li><a class='mettreenUne' data-toggle="modal" data-target="#mySmallModal" href='<?php echo $this->url(array('action'=>'post-home','controller'=>'articles','id_article'=>$this->article->id_article),'admin',true)?>?url_redirect=<?php echo urlencode($_SERVER["REQUEST_URI"])?>'><span class="glyphicon glyphicon-star"></span> Mettre à la une</a></li><?php endif ?>
                                        <li><a class='modifArticle' href='<?php echo $this->url(array('action' => 'edit-article', 'controller' => 'articles', 'id_article' => $this->article->id_article, 'url_retour' => urlencode($_SERVER["REQUEST_URI"])), 'admin', true) ?>'><span class="glyphicon glyphicon-pencil"></span> Modifier article</a></li>
                                        <li><a class='modifPhotos' data-toggle="modal" data-target="#myLargeModal" href='<?php echo $this->url(array('action' => 'edit-picture', 'controller' => 'articles', 'id_article' => $this->article->id_article), 'admin', true) ?>'><span class="glyphicon glyphicon-picture"></span> Gestion photo ou video</a></li>
                                        <li><a class="addFile" data-toggle="modal" data-target="#myLargeModal" href='<?php echo $this->url(array('action' => 'add-file', 'controller' => 'articles', 'id_article' => $this->article->id_article), 'admin', true) ?>'><span class="glyphicon glyphicon-paperclip"></span> Gestion fichiers</a></li>
                                        <li class="divider"></li>
                                        <?php if ($this->article->inscription_fct): ?>
                                            <li><a href='<?php echo $this->url(array('action' => 'synthese-inscription', 'id_article' => $this->article->id_article), 'action', true) ?>'><span class="glyphicon glyphicon-list-alt"></span> Synthèse Inscriptions</a></li>
                                            <li><a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'envoi-mail-inscrits', 'id_article' => $this->article->id_article, 'url_retour' => urlencode($_SERVER["REQUEST_URI"])), 'admin', true) ?>"><span class="glyphicon glyphicon-envelope"></span> Envoyer un email aux inscrits</a></li>
                                            <li class="divider"></li>
                                        <?php endif ?>
                                        <li><a class='supArticle' href='<?php echo $this->url(array('action' => 'delete-article', 'controller' => 'articles', 'id_article' => $this->article->id_article), 'admin', true) ?>?comHash=<?php echo md5($this->article->id_article) ?>' title="Supprimer article"><span class="glyphicon glyphicon-remove"></span> Supprimer</a></li>
                                    </ul>
                                </div>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ANNONCES) && !$this->ajax): ?>
                                <div class="actions btn-group-sm">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                        Actions <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                        <li><a data-toggle="modal" data-target="#mySmallModal" title="<?php echo $this->article->hide_home ? "Mettre à la Une" : "Retirer de la Une" ?>" class="voir" href='<?php echo $this->url(array('action' => 'post-home', 'controller' => 'articles', 'id_article' => $this->article->id_article), 'admin', true) ?>?url_redirect=<?php echo urlencode($_SERVER["REQUEST_URI"]) ?>'><span class="glyphicon glyphicon-star"></span> <?php echo $this->article->hide_home ? "Mettre à la Une" : "Retirer de la Une" ?></a></li>
                                        <li><a title="Contacter annonceur" class="voir" href='<?php echo $this->url(array('controller' => 'articles', 'action' => 'envoi-mail-annonceur', 'id_annonce' => $this->article->id_article, 'url_retour' => urlencode($_SERVER["REQUEST_URI"])), 'admin', true) ?>'><span class="glyphicon glyphicon-envelope"></span> Contacter l'annonceur</a></li>
                                        <li class="divider"></li>
                                        <li><a data-toggle="modal" data-target="#mySmallModal" title="Supprimer" class="voir supArticle" href='<?php echo $this->url(array('action' => 'delete-annonce', 'controller' => 'articles', 'id_article' => $this->article->id_article), 'admin', true) ?>?return=cours'><span class="glyphicon glyphicon-remove"></span> Supprimer</a></li>
                                    </ul>
                                </div>
                            <?php endif ?>
                        <?php endif ?>
                        <div class="col-md-3">
                            <div class="visuel">
                                <?php if ($this->article->picture): ?>
                                    <a class="popupVideo" data-toggle="modal" data-target="#myLargeModal" href='<?php echo $this->url(array('action' => 'diaporama', 'id_article' => $this->article->id_article), 'action', true) ?>'>
                                        <?php if ($this->article->nbPhotos > 1): ?>
                                            <div class="cycle-slideshow" data-cycle-speed="200" data-cycle-timeout="2000">
                                                <?php foreach ($this->article->getIdPhotos(20) as $key => $id_photo): ?>
                                                    <img class="<?php echo $key == 0 ? " " : "hidden " ?>img-responsive center-block background" src='/images/upload/<?php echo $this->article->id_article ?>/thumb<?php echo $id_photo ?>' alt='image<?php echo $this->article->id_article ?>' />
                                                <?php endforeach; ?>
                                            </div>
                                            <div class="nbPhotos">
                                                <span class="glyphicon glyphicon-camera"></span> <?php echo $this->article->nbPhotos ?>
                                            </div>
                                            <span class="iconeLoupe"></span>
                                        <?php else: ?>
                                            <img class="img-responsive center-block background" src='/images/upload/<?php echo $this->article->id_article ?>/thumb<?php echo $this->article->picture ?>.<?php echo $this->article->extension ?>' alt='image<?php echo $this->article->id_article ?>' />
                                        <?php endif ?>
                                    </a>
                                <?php elseif ($this->article->youtube): ?>
                                    <a class="popupVideo" data-toggle="modal" data-target="#myLargeModal" href='<?php echo $this->url(array('action' => 'video', 'id_article' => $this->article->id_article), 'action', true) ?>'>
                                        <img class="img-responsive center-block background" src='//img.youtube.com/vi/<?php echo $this->article->youtube ?>/0.jpg' alt='image<?php echo $this->article->id_article ?>' />
                                        <span class="iconePlay"></span>
                                    </a>
                                <?php else: ?>
                                    <img class="img-responsive center-block background" src='/images/no-photo<?php echo $this->article->annonce ? "-annonce" : "" ?>.jpg' alt='image<?php echo $this->article->id_article ?>' />
                                <?php endif ?>
                            </div>
                        </div>
                        <div class="content col-md-9" id="article<?php echo $this->article->id_article ?>">
                            <div><h3><?php echo mb_strtoupper($this->article->title); ?><?php if ($this->article->annonce): ?><small class="pull-right">Référence annonce : <?php echo $this->article->id_article ?></small><?php endif ?></h3></div>
                            <?php if ($this->article->link_event && $this->article->start_date): ?>
                                <div class="text-info">
                                    <h4>
                                        <span class="glyphicon glyphicon-calendar"></span> 
                                        <?php $start_date = $this->article->getDate("start_date") ?>
                                        <?php $end_date = $this->article->getDate("end_date") ?>
                                        <?php $start_hour = $this->article->getHour("start_hour") ?>
                                        <?php $end_hour = $this->article->getHour("end_hour") ?>
                                        <?php if ($this->article->end_date != $this->article->start_date): ?>
                                            Du <?php echo $start_date->get(Aurel_Date::WEEKDAY) . ' ' . $start_date->get(Aurel_Date::DAY) . ' ' . $start_date->get(Aurel_Date::MONTH_NAME) ?>  
                                            <?php if ($this->article->with_hours): ?>
                                                à <?php echo $start_hour ?>
                                            <?php endif ?>
                                            au <?php echo $end_date->get(Aurel_Date::WEEKDAY) . ' ' . $end_date->get(Aurel_Date::DAY) ?> <?php echo $end_date->get(Aurel_Date::MONTH_NAME) ?> <?php echo $end_date->get(Aurel_Date::YEAR) ?> 
                                            <?php if ($this->article->with_hours): ?>
                                                à <?php echo $end_hour ?>
                                            <?php endif ?>
                                        <?php else: ?>
                                            Le <?php echo $start_date->get(Aurel_Date::DATE_FULL) ?> 
                                            <?php if ($this->article->with_hours): ?>
                                                <?php echo $this->article->start_hour != $this->article->end_hour ? "de" : "à" ?> <?php echo $start_hour ?>
                                                <?php if ($this->article->start_hour != $this->article->end_hour): ?>
                                                    à <?php echo $end_hour ?>
                                                <?php endif ?>
                                            <?php endif ?>
                                        <?php endif ?>
                                    </h4>
                                </div>
                            <?php endif ?>
                            <div class="contentMin"><?php echo $this->article->content; ?></div>
                            <div class="row">
                                <div class="col-md-4"></div>
                                <div class="col-md-4"></div>
                                <div class="col-md-4">
                                    <?php if ($this->article->names): ?>
                                        <a name='telechargement-<?php echo $this->article->id_article ?>'></a>
                                        <fieldset class="telechargements">
                                            <legend>Téléchargements</legend>
                                            <div class='row'>
                                                <?php $files = explode(",", $this->article->names) ?>
                                                <?php $id_files = explode(",", $this->article->id_files) ?>
                                                <?php foreach ($files as $key => $file): ?>
                                                    <?php $extension = pathinfo($file, PATHINFO_EXTENSION) ?>
                                                    <?php $id_file = $id_files[$key] ?>
                                                    <div class="col-md-4 text-center file-<?php echo $id_file ?>">
                                                        <a title="<?php echo $file ?>" class="fileLink" href='<?php echo $this->url(array('action' => 'download', 'id_file' => $id_file), 'action', true) ?>'>
                                                            <img src='/images/icons/32/<?php echo $extension ?>.gif' alt='icon' style="vertical-align: middle" />
                                                        </a>
                                                        <?php /* ?><div class="actionsDl">
                                                          <a class="colorbox" href='<?php echo $this->url(array('action'=>'rename-file','controller'=>'articles','id_article'=>$this->article->id_article,'id_file'=>$id_file),'admin',true)?>' style="float:left" title="Renommer fichier"><span class="ui-icon ui-icon-pencil"></span></a>
                                                          <a class="supFile" href='<?php echo $this->url(array('action'=>'delete-file','controller'=>'articles','id_article'=>$this->article->id_article,'id_file'=>$id_file),'admin',true)?>?comHash=<?php echo md5($id_file)?>' style="float:left" title="Supprimer fichier"><span class="ui-icon ui-icon-close"></span></a>
                                                          </div> */ ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        </fieldset>
                                    <?php endif ?>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <div class="<?php echo $this->article->inscription_fct ? "text-center alert alert-info" : "" ?>">
                                        <?php if ($this->article->inscription_fct && Aurel_Date::now()->get(Aurel_Date::MYSQL_DATE) <= $this->article->inscription_date_limite): ?>
                                            <?php if ($this->hasParticipate): ?>
                                                Vous êtes inscrit à cet événement<br/>
                                                <?php foreach ($this->tabLibelle as $id_inscription => $name): ?>
                                                    <?php if (isset($this->tabQuantites[$id_inscription])): ?>
                                                        <div><?php echo $name ?> : <?php echo isset($this->tabQuantites[$id_inscription]) ? $this->tabQuantites[$id_inscription] : 0 ?></div>
                                                    <?php endif ?>
                                                <?php endforeach ?>
                                            <?php endif ?>
                                            <a data-toggle="modal" data-target="#myModal" class="btn btn-primary" href="<?php echo $this->url(array('action' => 'participer', 'id_article' => $this->article->id_article), 'action', true) ?>">
                                                <?php if (!$this->hasParticipate): ?>
                                                    Je m'inscris à l'événement
                                                <?php else: ?>
                                                    Modifier mon inscription
                                                <?php endif; ?>
                                            </a>
                                            <br/><br/>
                                            <a data-toggle="modal" data-target="#myModal" href="<?php echo $this->url(array('action' => 'synthese-inscription', 'id_article' => $this->article->id_article), 'action', true) ?>"><span class="glyphicon glyphicon-user"></span> Voir les inscrits</a>
                                        <?php elseif ($this->article->inscription_fct && $this->hasParticipate): ?>
                                            Vous étiez inscrit à cet événement<br/>
                                            <?php foreach ($this->tabLibelle as $id_inscription => $name): ?>
                                                <div><?php echo $name ?> : <?php echo $this->tabQuantites[$id_inscription] ?></div>
                                            <?php endforeach ?>

                                            <br/><br/>
                                            <a data-toggle="modal" data-target="#myModal" href="<?php echo $this->url(array('action' => 'synthese-inscription', 'id_article' => $this->article->id_article), 'action', true) ?>"><span class="glyphicon glyphicon-user"></span> Voir les inscrits</a>
                                        <?php endif ?>
                                    </div>
                                </div>
                            </div>
                            <?php if ($this->article->annonce): ?>
                                <div class="btn btn-success btn-lg"><strong>Prix : </strong><?php echo $this->article->prix != '' ? $this->article->prix : 'A négocier' ?></div>
                            <?php endif; ?>
                            <?php if ($this->article->id_sondage): ?>
                                <div class="row text-center">
                                    <hr/>
                                    <a class="btn btn-warning" href="<?php echo $this->url(array('basename_sondage' => $this->sondage->basename, 'url_redirect' => urlencode($this->url())), 'basename_sondage', true) ?>">Répondre à l'enquête</a>
                                </div>
                            <?php endif ?>
                        </div>
                    </div>
<?php endif ?>
            </div>
        </div>
<?php if ($this->article->annonce && !$this->ajax): ?>
            <div class="col-sm-4 col-sm-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">Contacter l'annonceur</div>
                    <div class="panel-body text-center">
                        <div><a class="btn btn-primary" data-toggle="modal" data-target="#myModal" href='<?php echo $this->url(array('action' => 'contact-annonceur', 'id_annonce' => $this->article->id_article), 'action', true) ?>'><span class="glyphicon glyphicon-envelope"></span> Envoyer un email</a></div>
    <?php if (!$this->article->masque_tel && $this->annonceur->tel): ?>
                            <br/>Contacter moi par <span class="glyphicon glyphicon-earphone"></span> :<br/><div class=""><h3><?php echo $this->annonceur->tel ?></h3></div><?php endif ?>
                    </div>
                </div>
            </div>
        <?php endif ?>
    <?php if ($this->ajax): ?>
        </div>
<?php endif ?>
</div>
<script type="text/javascript">
    $(document.body).on('hidden.bs.modal', function () {
        $('.cycle-slideshow').cycle('resume');
    });
    $(function () {
<?php if ($this->ajax): ?>
            $('.cycle-slideshow').cycle();
<?php endif ?>
        $('.fileLink').tooltip();
<?php if (!$this->article->annonce): ?>
    <?php if ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES) || ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_REDACTEUR) && $this->article->id_user_creation == $this->user->id_user)): ?>
                $.fn.modal.Constructor.prototype.enforceFocus = function () {
                    modal_this = this
                    $(document).on('focusin.modal', function (e) {
                        if (modal_this.$element[0] !== e.target && !modal_this.$element.has(e.target).length
                                // add whatever conditions you need here:
                                &&
                                !$(e.target.parentNode).hasClass('cke_dialog_ui_input_select') && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_text')) {
                            modal_this.$element.focus()
                        }
                    })
                };
                $(".checkboxSwitch").bootstrapSwitch();
                $(".checkboxSwitch").on('switchChange.bootstrapSwitch', function (event, state) {
                    var id_article = $(this).val();
                    $.post(
                            "<?php echo $this->url(array('action' => 'toggle-article', 'controller' => 'articles'), 'admin', true) ?>",
                            {"id_article": id_article, "state": state}
                    );
                });
                $('.supArticle').click(function () {
                    return confirm("Etes vous sur de vouloir supprimer cet article ?");
                });
    <?php endif ?>
<?php endif ?>

        $('.popupVideo').click(function () {
            $('.cycle-slideshow').cycle('pause');
        });
        $('.cycle-slideshow img').removeClass('hidden');



<?php if ($this->valideParticipation == '1'): ?>
            $('#mySmallModal .modal-content').html('<div class="modal-body"><div class="text-center">Votre participation a bien été prise en compte</div></div><div class="modal-footer"><button type="button" class="btn btn-primary" data-dismiss="modal">Fermer</button></div>');
            $('#mySmallModal').modal('show');
<?php endif ?>

<?php if ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES)): ?>
            $('.inputFilePhoto').change(function () {
                var Formdata = new FormData($("#frmuploadphoto")[0]);

                $.ajax({
                    url: "<?php echo $this->url(array("controller" => "photos", "action" => "upload-photo-site", "page" => "menu", "id_menu" => $this->menu->id_menu, "id_sous_menu" => $this->sousmenu ? $this->sousmenu->id_sous_menu : null), "admin", true) ?>",
                    data: Formdata,
                    cache: false,
                    contentType: false,
                    processData: false,
                    dataType: 'json',
                    type: 'POST',
                    beforeSend: function () {
                        $('.progress .progress-bar').css('width', '0%').prop('aria-valuenow', 0);
                        $('.progress').fadeIn();
                    },
                    xhr: function () {
                        var xhr = new window.XMLHttpRequest();
                        //Download progress
                        xhr.addEventListener("progress", function (evt) {
                            if (evt.lengthComputable) {
                                var percentComplete = Math.round(evt.loaded * 100 / evt.total);
                                $('.progress .progress-bar').css('width', percentComplete + '%').prop('aria-valuenow', percentComplete);
                                $('.progress .progress-bar .number').text(percentComplete);
                            }
                        }, false);
                        return xhr;
                    },
                    success: function (response) {
                        if (response.message) {
                            $("#messages").html(response.message);
                            if (response.valid == true) {
                                $("#messages").addClass('alert alert-success');
                            } else {
                                $("#messages").addClass('alert alert-danger');
                            }
                        }
                        if (response.picture_url) {
                            $('.backgroundimage').css('background-image', 'url(' + response.picture_url + ')');
                        }
                    }
                });
            });
<?php endif ?>
    });
</script>