<div class="backgroundimage" style="background-image:url(/images/upload/<?php echo !$this->sousmenu ? 'menu'.$this->menu->id_menu.'/'.$this->menu->picture : 'sousmenu'.$this->sousmenu->id_sous_menu.'/'.$this->sousmenu->picture; ?>)">
    <?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES)):?>
        <form id="frmuploadphoto" method="post" class="form-horizontal" role="form" enctype="multipart/form-data" action="<?php echo $this->url(array("controller"=>"photos","action"=>"upload-photo-site","page"=>"home"),"admin",true) ?>">
            <div class="blockUploadPhoto text-center">
                <div class="wait hidden"><img src='/images/wait.gif' alt='wait' /></div>
                <div class="header text-center">Modifier background</div>
                <div class="buttonUpload text-center">
                    <?php echo $this->formButton("buttonfile","Choisir le fichier",array('class'=>'btn btn-success btn-xs'))?>
                </div>
                <input type="file" class="inputFilePhoto" name="photo" />
                <?php echo $this->formHidden("file",'home',array('class'=>'fileHidden'))?>

                <div class="progress center-block" style="width: 150px;display: none">
                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                        <span class="number">0</span>%
                    </div>
                </div>
            </div>
        </form>
    <?php endif ?>
    <div class="pictureTop">
        <a href="<?php echo $this->url(array(),'accueil',true) ?>">Home</a> /
        <?php if(!$this->sousmenu):?><a href="<?php echo $this->url(array('basename_principal'=>$this->menu->basename),'basenames',true) ?>"><?php endif?><?php echo $this->menu->name?><?php if(!$this->sousmenu):?></a><?php endif?>
        <?php if($this->sousmenu && $this->menu):?>
            / <a href="<?php echo $this->url(array('basename_principal'=>$this->menu->basename,'basename_secondaire'=>$this->sousmenu->basename),'basenames',true) ?>"><?php echo $this->sousmenu->name?></a>
        <?php endif?>
        <?php if($this->article):?>
            / <a href="<?php echo $this->url() ?>"><?php echo $this->article->title?></a>
        <?php endif?>
    </div>
	<div id="popupArticles">
		<?php if($this->popupArticles && ($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES) || $this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_REDACTEUR) && isset($this->menus_redacteur[$this->menu->id_menu][$this->sousmenu->id_sous_menu]) && $this->menus_redacteur[$this->menu->id_menu][$this->sousmenu->id_sous_menu] == "1")):?>
		<div class="text-center"><a class="btn btn-default addArticle" href='<?php echo $this->url(array('action'=>'edit-article','controller'=>'articles','id_article'=>null,'basename_principal'=>$this->basename_principal,'basename_secondaire'=>$this->basename_secondaire,'url_retour'=>urlencode($_SERVER["REQUEST_URI"])),'admin',true)?>'><span class="glyphicon glyphicon-plus"></span> Ajouter un article</a></div>
		<?php endif?>
		<div class="articles">
			<?php echo $this->render('index/articles-in-page.phtml')?>
		</div>
		<?php if($this->hasOlder):?>
		<div class="text-center">
			<a href='<?php echo $this->urlLink;?>' data-loading-text="Chargement..." class='downloadOlder btn btn-success btn-sm'><?php echo $this->textLink?></a>
		</div>
		<?php endif?>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		<?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES) || $this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_REDACTEUR)):?>
		$.fn.modal.Constructor.prototype.enforceFocus = function () {
		    modal_this = this
		    $(document).on('focusin.modal', function (e) {
		        if (modal_this.$element[0] !== e.target && !modal_this.$element.has(e.target).length
		        // add whatever conditions you need here:
		        &&
		        !$(e.target.parentNode).hasClass('cke_dialog_ui_input_select') && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_text')) {
		            modal_this.$element.focus()
		        }
		    })
		};
		
		$(".checkboxSwitch").bootstrapSwitch();
		$(".checkboxSwitch").on('switchChange.bootstrapSwitch', function(event, state) {
			  var id_article = $(this).val();
			  $.post(
				"<?php echo $this->url(array('action'=>'toggle-article','controller'=>'articles'),'admin',true)?>",
				{"id_article":id_article,"state":state}
			  );	
		});
		$('.supArticle').click(function(){
			return confirm("Etes vous sur de vouloir supprimer cet article ?");
		});
		<?php endif?>
		$('.cycle-slideshow').cycle('pause');

		$('.hover').hover(function(){
			$(this).find('.cycle-slideshow').cycle('resume').cycle('goto', 1);
		},function(){
			$(this).find('.cycle-slideshow').cycle('pause').cycle('goto', 0);
		});
		$('.cycle-slideshow img').removeClass('hidden');

		<?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES)):?>
		$(".articles").sortable({
			items: "div.article",
			handle: ".orderArticle",
			start: function(event, ui) {
				//$('.actualitesinfo').removeClass('lastcolonnes').removeClass('colonnes');
				//$('.actualitesinfo hr.hidden-xs').removeClass('hidden');
			},
			update: function(event, ui) {
				order = $(this).sortable("toArray").toString();
				$.post(
					'<?php echo $this->url(array('action' => 'sort-articles-rubrique','controller'=>'articles'),'admin',true)?>',
					'order='+order,
					function(data, textStatus, XMLHttpRequest){
					
					}
				);
			}
		});
		<?php endif?>


        <?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES)):?>
        $('.inputFilePhoto').change(function(){
            var Formdata = new FormData($("#frmuploadphoto")[0]);

            $.ajax({
                url: "<?php echo $this->url(array("controller"=>"photos","action"=>"upload-photo-site","page"=>"menu","id_menu" => $this->menu->id_menu,"id_sous_menu"=>$this->sousmenu ? $this->sousmenu->id_sous_menu : null),"admin",true) ?>",
                data: Formdata,
                cache: false,
                contentType: false,
                processData: false,
                dataType : 'json',
                type: 'POST',
                beforeSend: function () {
                    $('.progress .progress-bar').css('width','0%').prop('aria-valuenow',0);
                    $('.progress').fadeIn();
                },
                xhr: function () {
                    var xhr = new window.XMLHttpRequest();
                    //Download progress
                    xhr.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = Math.round(evt.loaded * 100 / evt.total);
                            $('.progress .progress-bar').css('width',percentComplete + '%').prop('aria-valuenow',percentComplete);
                            $('.progress .progress-bar .number').text(percentComplete);
                        }
                    }, false);
                    return xhr;
                },
                success: function(response){
                    if(response.message){
                        $("#messages").html(response.message);
                        if(response.valid == true){
                            $("#messages").addClass('alert alert-success');
                        } else {
                            $("#messages").addClass('alert alert-danger');
                        }
                    }
                    if(response.picture_url){
                        $('.backgroundimage').css('background-image','url(' + response.picture_url + ')');
                    }
                }
            });
        });
        <?php endif ?>

		$('.downloadOlder').click(function(){
			var btn = $(this)
		    btn.button('loading');
			$.get(
				$(this).prop('href'),
				function(response){
					if(response.ids){
						for(i in response.ids){
							$('#article-' + response.ids[i]).remove();
						}
					}
					if(response.html){
						$('.articles').append(response.html);
					}
					if(response.urlLink){
						$('.downloadOlder').prop('href',response.urlLink);
					}
					if(response.textLink){
						$('.downloadOlder').html(response.textLink);
					}
					if(!response.hasOlder){
						$('.downloadOlder').parent().hide();
					}
					<?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_ARTICLES) || $this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN_REDACTEUR)):?>
						$(".checkboxSwitch").bootstrapSwitch();
						$(".checkboxSwitch").on('switchChange.bootstrapSwitch', function(event, state) {
							  var id_article = $(this).val();
							  $.post(
								"<?php echo $this->url(array('action'=>'toggle-article','controller'=>'articles'),'admin',true)?>",
								{"id_article":id_article,"state":state}
							  );
						});
						$('.supArticle').click(function(){
							return confirm("Etes vous sur de vouloir supprimer cet article ?");
						});
					<?php endif?>
					btn.button('reset');
				},'json'
			);
			return false;
		});
	});
</script>