<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title" id="myModalLabel"><?php echo $this->article->title?></h4>
</div>
<div class="modal-body">
	<div class="video-container">
		<iframe width="640" height="360" src="//www.youtube.com/embed/<?php echo $this->video?>?autoplay=1&autohide=1&color=white&showinfo=0&theme=light&rel=0" frameborder="0" allowfullscreen></iframe>
	</div>
</div>
