<div>
	<div class="text-center">
	<a class='empty btn btn-warning' href='<?php echo $this->url(array('action'=>'empty-trash','controller'=>'articles'),'admin',true)?>' title="Vider corbeille"><span class="glyphicon glyphicon-trash"></span> Vider la corbeille</a>
	</div>
	<?php foreach($this->articles_corbeilles as $article):?>
		<div class="media row article articleTronque" id="article-<?php echo $article->id_article?>">
			<?php if($this->isAllowed(Aurel_Acl::RESSOURCE_ADMIN)):?>
			<div class="actions btn-group-sm">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
					Actions <span class="caret"></span>
				</button>
				<ul class="dropdown-menu dropdown-menu-right" role="menu">
					<li><a class='restoreArticle' href='<?php echo $this->url(array('action'=>'restore','controller'=>'articles','id_article'=>$article->id_article),'admin',true)?>?comHash=<?php echo md5($article->id_article)?>' title="Supprimer article"><span class="glyphicon glyphicon-retweet"></span> Restaurer</a></li>
					<li><a class='supArticle' href='<?php echo $this->url(array('action'=>'delete-article','controller'=>'articles','id_article'=>$article->id_article,'definit'=>1),'admin',true)?>?comHash=<?php echo md5($article->id_article)?>' title="Supprimer article"><span class="glyphicon glyphicon-remove"></span> Supprimer définitivement</a></li>
				</ul>
			</div>
			<?php endif?>
			<?php if($article->link_event && $article->start_date):?>
				<div class="date_cartouche">
					<span class="day_of_month"><?php echo $article->getDate('start_date')->get(Aurel_Date::DAY)?></span>
					<span class="month_name"><?php echo mb_strtoupper($article->getDate('start_date')->get(Aurel_Date::MONTH_NAME_SHORT))?></span>
				</div>
			<?php endif?>
			<div class="col-xs-5 col-md-3">
				<div class="visuel">
					<?php if($article->picture):?>
						<?php if($article->nbPhotos > 1):?>
						<div class="cycle-slideshow" data-cycle-speed="200" data-cycle-timeout="1000">
							<?php foreach($article->getIdPhotos() as $key=>$id_photo):?>
						    <img class="<?php echo $key == 0 ? " " : "hidden "?>img-responsive" src='/images/upload/<?php echo $article->id_article?>/thumb<?php echo $id_photo?>' alt='image<?php echo $article->id_article?>' />
						    <?php endforeach;?>
						</div>
						<div class="nbPhotos">
							<span class="glyphicon glyphicon-camera"></span> <?php echo $article->nbPhotos?>
						</div>
						<?php else:?>
						<img class="img-responsive" src='/images/upload/<?php echo $article->id_article?>/thumb<?php echo $article->picture?>.<?php echo $article->extension?>' alt='image<?php echo $article->id_article?>' />
						<?php endif?>
					<?php elseif($article->youtube):?>
						<div class="popupVideo">
							<img class="img-responsive" src='http://img.youtube.com/vi/<?php echo $article->youtube?>/0.jpg' alt='image<?php echo $article->id_article?>' />
							<span class="iconePlay"></span>
						</div>
					<?php else: ?>
						<img class="img-responsive" src='/images/no-photo.jpg' alt='image<?php echo $article->id_article?>' />
					<?php endif?>
				</div>
			</div>
			<div class="content col-xs-7 col-md-9" id="article<?php echo $article->id_article?>">
				<div><h3 class="underline"><?php echo mb_strtoupper($article->title);?></h3></div>
				<div class="hidden-xs contentTronque"><?php echo strip_tags($article->content,"<br>");?></div>
				<div>
				<?php if($article->names):?>
					<?php $files = explode(",",$article->names)?>
					<div class="btn btn-success btn-sm"><span class="glyphicon glyphicon-paperclip"></span> <?php echo count($files)?> fichier<?php echo count($files) == 1 ? "" : "s"?> joint<?php echo count($files) == 1 ? "" : "s"?></div>
				<?php endif?>
				</div>					
			</div>
			<div class="bottom">
				<div class="col-md-3"></div>
				<div class="col-md-9">
					<div class="bottomRight"><strong>Publié le <?php echo $article->getDate('date_modification')->get(Aurel_Date::DATE_MEDIUM)?></strong></div>
				</div>
			</div>
		</div>
	<?php endforeach;?>
</div>
<script type="text/javascript">
	$(function(){
		$('.supArticle').click(function(){
			return confirm("Etes vous sur de vouloir supprimer définitivement cet article ?");
		});
		$('.empty').click(function(){
			return confirm("Etes vous sur de vouloir supprimer définitivement tous les articles de la corbeille ?");
		});
	});
</script>