<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title" id="myModalLabel"><?php echo $this->menu->id_menu ? "Editer Menu" : "Ajouter Menu"?></h4>
</div>
<form method='post' action='<?php echo $this->url()?>' role="form">
	<div class="modal-body">
		<div class="form-group">
			<?php echo $this->formLabel('name','Nom du menu')?>
			<?php echo $this->formText('name',$this->menu->name,array('placeholder'=>'Nom du menu',"class"=>"form-control"))?>
		</div>
        <div class="form-group">
            <?php echo $this->formHidden('agenda',null)?>
            <?php echo $this->formHidden('annonces',null)?>
            <div class="checkbox">
                <label><?php echo $this->formCheckbox('news',null,array("class"=>"","checked"=>$this->menu->news))?> Menu Actualités</label>
            </div>
        </div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
			<?php echo $this->formSubmit('valider','Enregistrer les modifications',array('class'=>'btn btn-primary','data-loading-text'=>"Loading..."))?>
		</div>
	</div>
</form>
<script type="text/javascript">
$(function(){
	
});
</script>