<?php echo $this->doctype()?>
<html lang="fr" prefix="og: http://ogp.me/ns#">
	<head>
		<?php echo $this->headMeta()?>
		<?php echo $this->headTitle()?>
		<?php echo $this->headScript()?>
		<?php echo $this->headLink()?>
		<?php echo $this->headStyle()?>
	</head>
	<body>
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.0";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', 'UA-48148408-2', 'lepetitcharsien.com');
		  ga('send', 'pageview');
		
		</script>
		<div>
			<?php echo $this->layout()->content ?>
		</div>
    <?= $this->render('axeptio.phtml') ?>
	</body>
</html>