<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta content="width=device-width">
		<style type="text/css">
	    /* Fonts and Content */
	    body, td { font-family: 'Helvetica Neue', Arial, Helvetica, Geneva, sans-serif; font-size:14px; }
	    body { background-color: #f3f3f3; margin: 15px 0; padding: 0; -webkit-text-size-adjust:none; -ms-text-size-adjust:none; }
	    
	    </style>
	</head>
	<body style="background-color: #f3f3f3; margin:15px 0; padding:0px; -webkit-text-size-adjust:none;">
		<?php echo $this->layout()->content ?>
	</body>
</html>