<?php echo $this->render('annuaire/tabs.phtml')?>
<div class="nav-tabs-content">
    <div class="form-group">
        <a class="btn btn-default" href="<?php echo $this->url(array(),"annuairedownload",true)?>"><img src="/images/icons/32/pdf.gif" alt="pdf" /> Annuaire PDF</a>
        <a class="btn btn-default" href="<?php echo $this->url(array(),"annuairedownloadcsv",true)?>"><img src="/images/icons/32/xls.gif" alt="xls" /> Tableau Excel</a>
    </div>
</div>