<ul class="myTab nav nav-tabs" role="tablist">
    <li class="active"><a href='#home' role="tab" data-toggle="tab">Utilisateurs Actifs</a></li>
    <li><a href='#profile' role="tab" data-toggle="tab">Utilisateurs Inactifs</a></li>
</ul>
<div class="nav-tabs-content tab-content">
    <div class="tab-pane active" id="home">
        <div class="text-center">
            <a class="btn btn-primary" href="<?php echo $this->url(array('action' => 'download')) ?>"><span class="glyphicon glyphicon-download-alt"></span> Télécharger BDD utilisateurs</a>
            <a class="btn btn-primary" href="<?php echo $this->url(array('action' => 'add-edit')) ?>"><span class="glyphicon glyphicon-plus"></span> Ajouter nouvel utilisateur</a>

            <a class="btn btn-primary" data-content="Envoyer notification" href="<?php echo $this->url(array('action' => 'send')) ?>"><span class="glyphicon glyphicon-envelope"></span> Envoyer notification à tous</a>
        </div>
        <hr>
        <div class="col-sm-3 col-sm-offset-9">
            <form method="get" action="<?php echo $this->url(array('p' => null, 'orderby' => null, 'order' => null)) ?>">
                <div class="input-group">
                    <?php echo $this->formText('search', $this->search, array('class' => 'form-control', 'placeholder' => 'Chercher un utilisateur')) ?>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                </div>
            </form>
        </div>
        <table class="table table-condensed article">
            <thead>
                <tr>
                    <th><a class="<?php echo $this->drop["lastname"] ?>" href='<?php echo $this->url($this->links['lastname']) . $this->addLink ?>'>Nom <span class="<?php echo $this->icones['lastname'] ?>"></span></a></th>
                    <th><a class="<?php echo $this->drop["firstname"] ?>" href='<?php echo $this->url($this->links['firstname']) . $this->addLink ?>'>Prénom <span class="<?php echo $this->icones['firstname'] ?>"></span></a></th>
                    <th><a class="<?php echo $this->drop["email"] ?>" href='<?php echo $this->url($this->links['email']) . $this->addLink ?>'>Email <span class="<?php echo $this->icones['email'] ?>"></span></a></th>
                    <th style="white-space:nowrap"><a class="<?php echo $this->drop["directeur"] ?>" href='<?php echo $this->url($this->links['directeur']) . $this->addLink ?>'>Dir. Pub <span class="<?php echo $this->icones['directeur'] ?>"></span></a></th>
                    <th><a class="<?php echo $this->drop["type"] ?>" href='<?php echo $this->url($this->links['type']) . $this->addLink ?>'>Droits <span class="<?php echo $this->icones['type'] ?>"></span></a></th>
                    <th><a class="<?php echo $this->drop["date_last_connexion"] ?>" href='<?php echo $this->url($this->links['date_last_connexion']) . $this->addLink ?>'>Dernière connexion <span class="<?php echo $this->icones['date_last_connexion'] ?>"></span></a></th>
                    <th></th>
                    <th class="text-right">Notification</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->usersActif as $key => $user) : ?>
                    <tr class="">
                        <td><?php echo $user->lastname ?></td>
                        <td><?php echo $user->firstname ?></td>
                        <td><?php echo $user->email ?></td>
                        <td class="text-center">
                            <div class="text-success"><?php echo $user->directeur ? "<span class='glyphicon glyphicon-ok'></span>" : "" ?></div>
                        </td>
                        <td>
                            <?php if ($user->rights()) : ?>
                                <a class="rights" href='#' data-content="<?php echo $user->rights() ?>">Voir les droits</a>
                            <?php endif ?>
                        </td>
                        <td><?php echo $user->date_last_connexion ? $user->getDate('date_last_connexion')->get(Aurel_Date::DATETIME) : "" ?></td>
                        <td class="actionsBtn">
                            <div><a class="btn btn-default btn-sm" data-content="Modifier" href="<?php echo $this->url(array('action' => 'add-edit', 'id_user' => $user->id_user)) ?>"><span class="glyphicon glyphicon-pencil"></span></a></div>
                            <div><a class="btn btn-default btn-sm" data-content="Déplacer vers utilisateurs inactifs" data-toggle="modal" data-target="#mySmallModal" href="<?php echo $this->url(array('action' => 'delete', 'id_user' => $user->id_user)) ?>"><span class="glyphicon glyphicon-trash"></span></a></div>
                        </td>
                        <td class="text-right">
                            <div><a class="btn btn-default btn-sm" data-content="Envoyer notification" href="<?php echo $this->url(array('action' => 'send', 'id_user' => $user->id_user)) ?>"><span class="glyphicon glyphicon-envelope"></span> Envoyer notification</a></div>

                            <?php if ($user->date_send) : ?>
                                <div class="small text-danger"><b>Dernière notification</b><br><?= $user->getDate('date_send')->get(Aurel_Date::DATETIME) ?></div>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="text-center">
            <?php echo $this->paginationControl($this->usersActif, 'elastic', 'users/paginator.phtml'); ?>
        </div>
    </div>
    <div class="tab-pane" id="profile">
        <table class="table table-hover table-condensed article">
            <thead>
                <tr>
                    <th>Identifiant</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Email</th>
                    <th>Type</th>
                    <th>Dernière connexion</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->usersInactif as $key => $user) : ?>
                    <tr class="<?php echo $user->status == Aurel_Table_User::STATUS_ACTIF ? "success" : "" ?>">
                        <td><?php echo $user->name ?></td>
                        <td><?php echo $user->lastname ?></td>
                        <td><?php echo $user->firstname ?></td>
                        <td><?php echo $user->email ?></td>
                        <td><?php echo $this->selectType[$user->type] ?></td>
                        <td><?php echo $user->date_last_connexion ? $user->getDate('date_last_connexion')->get(Aurel_Date::DATETIME) : "" ?></td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a class="btn btn-default" data-content="Modifier" data-toggle="modal" data-target="#myLargeModal" href="<?php echo $this->url(array('action' => 'add-edit', 'id_user' => $user->id_user)) ?>"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a class="btn btn-default" data-content="Supprimer Définitivement" data-toggle="modal" data-target="#mySmallModal" href="<?php echo $this->url(array('action' => 'delete', 'id_user' => $user->id_user)) ?>"><span class="glyphicon glyphicon-remove"></span></a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        $('.actionsBtn a').popover({
            trigger: 'hover',
            placement: 'top',
            container: 'body'
        });
        $('.rights').popover({
            trigger: 'hover',
            placement: 'top',
            container: 'body',
            'html': true
        });
    });
</script>